CREATE TABLE `cargowise_containers_new` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `JC_ContainerNum` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JS_UniqueConsignRef` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JS_HouseBill` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JS_BookingReference` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JS_PackingMode` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scac_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company_code` text COLLATE utf8mb4_unicode_ci,
  `JS_RL_NKOrigin` text COLLATE utf8mb4_unicode_ci,
  `JS_RL_NKDestination` text COLLATE utf8mb4_unicode_ci,
  `JS_TransportMode` text COLLATE utf8mb4_unicode_ci,
  `JS_ScreeningStatus` text COLLATE utf8mb4_unicode_ci,
  `JS_SystemLastEditTimeUtc` text COLLATE utf8mb4_unicode_ci,
  `container_count` int(11) DEFAULT NULL,
  `container_numbers` text COLLATE utf8mb4_unicode_ci,
  `actual_volume` double(10,3) DEFAULT NULL,
  `dep_date` text COLLATE utf8mb4_unicode_ci,
  `console` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipper_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_ref` text COLLATE utf8mb4_unicode_ci,
  `timestamp` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `steamshipLine` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `etaAtTerminal` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `etaAtDestination` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirmedOnBoardDate` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vesselArrivedDate` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dischargedDate` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emptyReturnedDate` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isRailMove` tinyint(1) DEFAULT NULL,
  `tradeType` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `equipmentType` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `voyageNumber` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vessel` json DEFAULT NULL,
  `portOfLoading` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `originPort` json DEFAULT NULL,
  `portOfDischarge` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `destinationPort` json DEFAULT NULL,
  `terminalAtPortOfDischarge` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `terminalAtDestinationPort` json DEFAULT NULL,
  `location` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `currentLocation` json DEFAULT NULL,
  `lastKnownPosition` json DEFAULT NULL,
  `holds` json DEFAULT NULL,
  `history` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `JS_PK` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JS_F3_NKPackType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JS_GoodsDescription` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JS_INCO` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JL_PK` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JL_PackageCount` int(11) DEFAULT NULL,
  `JL_F3_NKPackType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JL_Length` decimal(10,0) DEFAULT NULL,
  `JL_Height` decimal(10,0) DEFAULT NULL,
  `JL_Width` decimal(10,0) DEFAULT NULL,
  `JL_UnitOfDimension` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JL_ActualWeight` decimal(10,0) DEFAULT NULL,
  `JL_ActualWeightUQ` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JL_ActualVolume` decimal(10,0) DEFAULT NULL,
  `JL_Description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JL_MarksAndNumbers` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JC_SealNum` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RC_Code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `JT_OrderReference` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SM_PK` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SM_DB` int(11) DEFAULT NULL,
  `deliver_to` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consignee` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pickup_from` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipper` json DEFAULT NULL,
  `rail_addon` text COLLATE utf8mb4_unicode_ci,
  `arrival_date` text COLLATE utf8mb4_unicode_ci,
  `size` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weight` double DEFAULT NULL,
  `documents` json DEFAULT NULL,
  `package_records` json DEFAULT NULL,
  `container_records` json DEFAULT NULL,
  `console_shipment` json DEFAULT NULL,
  `carrier` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `masterBillNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `container_weight` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SM_ParentFK` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `open_track` json DEFAULT NULL,
  `delay_in_departure` float DEFAULT NULL,
  `delay_in_arrival` float DEFAULT NULL,
  `delay_status` enum('Delayed','On Time') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cargowise_error` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `latestStatus` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `milestones` json DEFAULT NULL,
  `derived_statuses` json DEFAULT NULL,
  `primary_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consignee_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `currentETA` datetime DEFAULT NULL,
  `updatedETA` datetime DEFAULT NULL,
  `currentETD` datetime DEFAULT NULL,
  `updatedETD` datetime DEFAULT NULL,
  `delay_arrival` int(11) DEFAULT NULL,
  `delay_departure` int(11) DEFAULT NULL,
  `flight_vessel` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `do_not_query` tinyint(1) DEFAULT '0',
  `currentActualArrival` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updatedActualArrival` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `currentActualDeparture` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updatedActualDeparture` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `delay_actual_arrival` int(11) DEFAULT NULL,
  `delay_actual_departure` int(11) DEFAULT NULL,
  `milestones_new` json DEFAULT NULL,
  `containerDetails` json DEFAULT NULL,
  `unit_length` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit_width` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit_height` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `milestones_reformed` json DEFAULT NULL,
  `latest_completed_delay` int(11) DEFAULT NULL,
  `latest_completed_actualDate` datetime DEFAULT NULL,
  `latest_completed_event` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_shipment` (`JS_UniqueConsignRef`)
) ENGINE=InnoDB AUTO_INCREMENT=2287 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `system_flags` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key_name` varchar(100) DEFAULT NULL,
  `key_value` varchar(255) DEFAULT NULL,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `key_name` (`key_name`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;